export const contactInfo = {
  email: 'khondokertalha@gmail.com',
  phone: '+880 1867-051845',
  phoneHref: 'tel:+8801867051845',
  whatsapp: '+880 1867-051845',
  whatsappHref: 'https://wa.me/8801867051845',
}

export const socials = [
  { label: 'GitHub', href: 'https://github.com/talha-khondoker' },
  { label: 'LinkedIn', href: 'https://linkedin.com/in/talha-khondoker' },
  { label: 'Facebook', href: 'https://facebook.com/YOUR_FACEBOOK' },
  { label: 'WhatsApp', href: 'https://wa.me/8801867051845' },
  { label: 'Email', href: 'mailto:khondokertalha@gmail.com' },
]

// Used by the hero code editor
export const skills = [
  {
    group: 'Languages',
    short: 'Languages',
    items: ['Python', 'JavaScript', 'HTML', 'C', 'C++'],
  },
  {
    group: 'Libraries / Frameworks',
    short: 'Frameworks',
    items: ['FastAPI', 'ReactJS', 'Tailwind CSS', 'Bootstrap', 'SQLAlchemy'],
  },
  {
    group: 'Technologies',
    short: 'Technologies',
    items: [
      'REST APIs',
      'MySQL',
      'SQLite',
      'Supabase',
      'JWT Authentication',
      'Role-Based Access Control',
    ],
  },
  {
    group: 'Tools',
    short: 'Tools',
    items: ['Git & GitHub', 'Docker', 'Render', 'Netlify'],
  },
]

// Used by the graphical Skills section. Set the levels honestly.
export const skillLevels = [
  {
    group: 'Frontend',
    items: [
      { name: 'React', level: 75 },
      { name: 'JavaScript', level: 80 },
      { name: 'HTML', level: 90 },
      { name: 'Tailwind CSS and DaisyUI', level: 80 },
    ],
  },
  {
    group: 'Backend',
    items: [
      { name: 'Python', level: 85 },
      { name: 'FastAPI', level: 80 },
      { name: 'REST APIs', level: 80 },
      { name: 'JWT and role-based access', level: 75 },
    ],
  },
  {
    group: 'Databases',
    items: [
      { name: 'MySQL', level: 70 },
      { name: 'SQLAlchemy', level: 75 },
      { name: 'SQLite', level: 75 },
      { name: 'Supabase', level: 55 },
    ],
  },
  {
    group: 'Programming and CS',
    items: [
      { name: 'C++', level: 80 },
      { name: 'C', level: 70 },
      { name: 'Data structures and algorithms', level: 75 },
    ],
  },
  {
    group: 'Tools',
    items: [
      { name: 'Git and GitHub', level: 75 },
      { name: 'Docker', level: 55 },
      { name: 'Render and Netlify', level: 70 },
    ],
  },
]

// No professional experience yet: the site shows a "ready to explore" card instead.
// Add objects here later ({ role, place, period, points: [] }) and the experience section can come back.
export const experience = []

export const softSkills = ['Critical Analysis', 'Quick Learner', 'Adaptability', 'Responsibility', 'Communication']

export const projects = [
  {
    slug: 'blood-donation-platform',
    title: 'Blood Donation & Emergency Assistance Platform',
    image: '/projects/blood-aid.png',
    summary:
      'A platform that connects blood donors with people who urgently need blood, with admin tools to manage users and requests.',
    description:
      'Signup, login, token refresh, password reset and protected routes are built on JWT authentication. Three user roles (users, donors and administrators) manage blood requests, donor responses and request statuses through responsive dashboards, with search, filtering, sorting and pagination across users, donors and blood requests. The backend is a FastAPI REST API with SQLAlchemy, and the interface is built with React.',
    stack: ['FastAPI', 'SQLAlchemy', 'SQLite', 'React', 'JWT', 'REST API'],
    live: 'https://blood-aid-assistance.netlify.app/',
    github: 'https://github.com/talha-khondoker',
    challenges: [
      'Designing role-based access so users, donors and admins each see only what they should.',
      'Keeping logins smooth with token refresh, password reset and protected routes.',
      'Combining search, filtering, sorting and pagination without confusing results.',
    ],
    improvements: [
      'Email or SMS alerts when a matching donor is found.',
      'Location-based donor matching.',
      'Move from SQLite to PostgreSQL for production use.',
      'Add automated tests and Docker deployment.',
    ],
  },
  // {
  //   slug: 'library-management-api',
  //   title: 'Library Management System API',
  //   image: '/projects/library-api.png',
  //   summary:
  //     'A REST API for managing books, members and library records, built with FastAPI and SQLAlchemy.',
  //   description:
  //     'A backend service that handles library data through clean REST endpoints, with request validation and a relational database. It includes interactive API documentation generated by FastAPI.',
  //   stack: ['FastAPI', 'SQLAlchemy', 'SQLite', 'Python', 'REST API'],
  //   live: null, // deploy on Render and add the /docs link here
  //   github: 'https://github.com/talha-khondoker/library-management-api',
  //   challenges: [
  //     'Modelling the relationships between books, members and borrowing records.',
  //     'Validating requests and returning clear, consistent error messages.',
  //     'Structuring routes, schemas and database code so the project stays easy to maintain.',
  //   ],
  //   improvements: [
  //     'JWT authentication with admin and member roles.',
  //     'Fines, due dates and overdue reminders.',
  //     'A React frontend for librarians and members.',
  //     'Tests, Docker and deployment on Render.',
  //   ],
  // },
  // {
  //   slug: 'portfolio-website',
  //   title: 'Personal Portfolio Website',
  //   image: '/projects/portfolio.png',
  //   summary:
  //     'This responsive portfolio, built with React and DaisyUI, with every section driven by one data file.',
  //   description:
  //     'A single-page portfolio with a floating navbar, an animated code-editor skills card, graphical skills, project detail pages, smooth scrolling, a dark and light theme, and a contact section. All content lives in one data file, so adding a project is a small edit.',
  //   stack: ['React', 'Vite', 'Tailwind CSS', 'DaisyUI', 'GSAP', 'Framer Motion', 'Lenis', 'React Router'],
  //   live: 'https://talha-khondoker-portfolio.netlify.app/',
  //   github: 'https://github.com/talha-khondoker/portfolio',
  //   challenges: [
  //     'Making the layout and navbar work well from small phones to large desktops.',
  //     'Combining smooth scrolling (Lenis), scroll animations (GSAP) and reveals (Framer Motion) without conflicts.',
  //     'Keeping content in one data file while still giving each project its own page.',
  //   ],
  //   improvements: [
  //     'A contact form that sends messages without opening an email app.',
  //     'A blog section for what I learn.',
  //     'Project filtering by technology.',
  //     'Automated tests and performance tuning.',
  //   ],
  // },
]

// Keep YOUR real handles here (replace the YOUR_..._HANDLE parts)
export const codingProfiles = [
  {
    platform: 'Codeforces',
    href: 'https://codeforces.com/profile/talhakhondoker',
    value: '323+',
    text: 'problems solved, peak rating 975.',
  },
  {
    platform: 'CodeChef',
    href: 'https://www.codechef.com/users/talhakhondoker',
    value: '2★',
    text: 'rating 1447 across 10 rated contests.',
  },
  {
    platform: 'LeetCode',
    href: 'https://leetcode.com/u/talhak01/',
    value: '60+',
    text: 'problems solved, mostly in C++.',
  },
]

export const education = [
  {
    title: 'BSc in Mathematics',
    place: 'M M College Jashore, National University',
    note: '2023 to present, 3rd year',
  },
  {
    title: 'Higher Secondary Certificate (HSC), Science',
    place: 'B A F Shaheen College Jashore',
    note: '2021, GPA 5.00',
  },
  {
    title: 'Secondary School Certificate (SSC), Science',
    place: 'B A F Shaheen College Jashore',
    note: '2019, GPA 4.72',
  },
]
